=== TeX-Live/xetex/libs/icu-release-3-4-source/data/xml/deprecatedList.dtd
<!--
    Copyright (c) 2004 International Business Machines Corporation and others. All rights reserved.

    DTD for the ICU deprecated-locales list.
-->

<!ELEMENT deprecatedList ( overrideDraft*, deprecates* ) >
<!ATTLIST deprecatedList version CDATA #FIXED "1.0" >

<!ELEMENT overrideDraft EMPTY >
<!ATTLIST overrideDraft locale NMTOKEN #REQUIRED >

<!ELEMENT deprecates ( alias | aliasLocale )* >
<!ATTLIST deprecates type NMTOKEN #REQUIRED >

<!ELEMENT alias EMPTY >
<!ATTLIST alias from CDATA #REQUIRED >
<!ATTLIST alias to CDATA #REQUIRED >
<!ATTLIST alias xpath CDATA #IMPLIED >

<!ELEMENT aliasLocale EMPTY >
<!ATTLIST aliasLocale locale CDATA #REQUIRED >

=== TeX-Live/xetex/libs/icu-release-3-4-source/data/xml/deprecatedList.xml
<?xml version="1.0" encoding="UTF-8" ?> 
<!DOCTYPE deprecatedList SYSTEM "deprecatedList.dtd" >

<!--
 Copyright (c) 2002-2005 International Business Machines Corporation and others. All rights reserved.
-->

<deprecatedList>
  <!-- list of locales which ICU will take anyway, regardless of draft status. Equivalent of '-f' on that locale. -->
<!--  <overrideDraft locale="as"/>
  <overrideDraft locale="as_IN"/> -->
  <overrideDraft locale="ar_EG"/>
  <overrideDraft locale="hr_HR"/>
  <overrideDraft locale="en_PK"/>
  <overrideDraft locale="ml"/>
  <overrideDraft locale="ml_IN"/>
  <overrideDraft locale="or"/>
  <overrideDraft locale="or_IN"/>
  <overrideDraft locale="sl_SI"/>
  <overrideDraft locale="sr_Cyrl"/>
  
  <!-- only for 3.4 -->
  <overrideDraft locale="as"/> 
  <overrideDraft locale="as_IN"/> 
  <overrideDraft locale="az"/> 
  <overrideDraft locale="az_AZ"/> 
  <overrideDraft locale="az_Cyrl"/> 
  <overrideDraft locale="sh_CS"/> 
  <overrideDraft locale="sr_CS"/> 
  <overrideDraft locale="sr_Cyrl_CS"/> 
  <overrideDraft locale="sr_Latn_CS"/> 
  <overrideDraft locale="uz"/> 
  <overrideDraft locale="uz_Cyrl"/>
  <overrideDraft locale="uz_Latn"/>
  <overrideDraft locale="uz_UZ"/>
  
  <!-- collation aliases -->
  <deprecates type="collation"> 
    <alias from="de__PHONEBOOK" to="de@collation=phonebook"  xpath="//ldml/collations/default[@type='phonebook']"/> 
    <alias from="es__TRADITIONAL" to="es@collation=traditional" xpath="//ldml/collations/default[@type='traditional']"/> 
    <alias from="hi__DIRECT" to="hi@collation=direct" xpath="//ldml/collations/default[@type='direct']"/> 
    <alias from="zh__PINYIN" to="zh@collation=pinyin" xpath="//ldml/collations/default[@type='pinyin']"/> 
    <alias from="zh_TW_STROKE" to="zh@collation=stroke" xpath="//ldml/collations/default[@type='stroke']"/> 
  </deprecates> 

  <!-- locale aliases (main) -->
  <deprecates type="main" > 
    <alias from="in" to="id" /> 
    <alias from="in_ID" to="id_ID" /> 
    <alias from="iw" to="he" /> 
    <alias from="iw_IL" to="he_IL" /> 
    <alias from="ja_JP_TRADITIONAL" to="ja_JP@calendar=japanese" xpath="//ldml/dates/calendars/default[@type='japanese']"/> 
    <alias from="ji" to="yi" /> 
    <alias from="jw" to="jv"/> 
    <alias from="no" to="nb"/> 
    <alias from="no_NO" to="nb_NO"/> 
    <alias from="no_NO_NY" to="nn_NO" /> 
    <alias from="th_TH_TRADITIONAL" to="th_TH@calendar=buddhist" xpath="//ldml/dates/calendars/default[@type='buddhist']" /> 
    <aliasLocale locale="az_AZ" /> 
    <aliasLocale locale="sh" /> 
    <aliasLocale locale="sh_BA" /> 
    <aliasLocale locale="sh_CS" /> 
    <aliasLocale locale="sh_YU" /> 
    <aliasLocale locale="sr_BA" /> 
    <aliasLocale locale="sr_CS" /> 
    <aliasLocale locale="sr_YU" /> 
    <aliasLocale locale="sr_Cyrl_YU" /> 
    <aliasLocale locale="sr_Latn_YU" /> 
    <aliasLocale locale="uz_AF" /> 
    <aliasLocale locale="uz_UZ" /> 
    <aliasLocale locale="zh_CN" /> 
    <aliasLocale locale="zh_HK" /> 
    <aliasLocale locale="zh_MO" /> 
    <aliasLocale locale="zh_SG" /> 
    <aliasLocale locale="zh_TW" />
  </deprecates> 
</deprecatedList>
